name: Build and Deploy

on:
  push:
    branches: [ main ]
    paths:
      - 'templates/**'
      - 'categories.yml'
      - 'src/**'
      - 'scripts/**'
      - 'example/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'templates/**'
      - 'categories.yml'
      - 'src/**'
      - 'scripts/**'
      - 'example/**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Validate templates
        run: npm run validate

  build:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install root dependencies
        run: npm install

      - name: Build library
        run: npm run build

      - name: Build API
        run: npm run build:api

      - name: Install example dependencies
        run: |
          cd example/github-pages-example
          npm install

      - name: Build GitHub Pages example
        run: |
          cd example/github-pages-example
          npm run build

      - name: Copy API to example dist
        run: |
          cp -r api example/github-pages-example/dist/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './example/github-pages-example/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4